<?php
//session_start();
if(isset($_SESSION["studentID"]) OR isset($_SESSION["programID"]))
            {
               echo "hello";
            }

?>
<div id="loginForm">    
        <div id="login_header">
                <div class="login_text">Election Management System <br></div>
                <div class="login_text2">University of the Immaculate Conception</div>
        </div>
        <p>
            Please enter your username given by the Comelec
            <br>and password generated by migz
        </p>
        <fieldset>
           <form action="../inc/checkUserId.php" method="POST">
            <br>
            <br><br>
            <input class="username" type="text" name="user_id" maxlength="7" placeholder="Username" required>
            <br>
            <input type="password" name="password" placeholder="Password" required>
            <br>
            <input class="submit" type="submit" value="Submit">
            <br>
            </form>
        </fieldset>
        </div>









